services:
  db:
    image: postgres:17.5-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  redis:
    image: redis/redis-stack:7.2.0-v15

  web:
    build:
      context: ./storefront-app
    ports:
      - "9191:9191"
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads/images:/app/uploads/images
    environment:
      DB_NAME: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      DB_HOST: db
      DB_PORT: 5432
      REDIS_PORT: 6379
      REDIS_HOST: redis

volumes:
  db_data: