services:
  db:
    image: postgres:17.5-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    command: start-dev --import-realm --http-port=8181
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "8181:8181"
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json

  redis:
    image: redis/redis-stack:7.2.0-v15

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "9192:9192"
    depends_on:
      - keycloak

  web:
    build:
      context: ./storefront-app
    ports:
      - "9191:9191"
    depends_on:
      - keycloak
      - db
      - redis
      - payment-service
    volumes:
      - ./uploads/images:/uploads/images
    environment:
      DB_NAME: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      DB_HOST: db
      DB_PORT: 5432
      REDIS_PORT: 6379
      REDIS_HOST: redis
      PAYMENT_SERVICE_HOST: payment-service
      PAYMENT_SERVICE_PORT: 9192


volumes:
  db_data: