spring:
  application:
    name: intershop
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    parameters:
      schemaName: public
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50

app:
  upload-dir: uploads/images/

server:
  port: 9191
  servlet:
    context-path: /intershop
  error:
    include-message: always

logging:
  level:
    root: INFO
    org:springframework.web: INFO
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 100MB



