spring:
  application:
    name: storefront-app

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    parameters:
      schemaName: public

  webflux:
    base-path: /intershop

app:
  upload-dir: uploads/images/
  payment-api:
    url: http://localhost:8080
  init:
    enabled: true


server:
  port: 9191
  error:
    include-message: always

logging:
  level:
    root: INFO
    org:springframework.web: INFO
    org.springframework.r2dbc.core: DEBUG
    org.springframework.data.redis.connection: DEBUG
  file:
    name: logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 100MB



