DELETE FROM order_item;
DELETE FROM orders;
DELETE FROM item;
DELETE FROM user_role;
DELETE FROM users;
DELETE FROM roles;


ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE roles ALTER COLUMN id RESTART WITH 1;
ALTER TABLE order_item ALTER COLUMN id RESTART WITH 1;
ALTER TABLE orders ALTER COLUMN id RESTART WITH 1;
ALTER TABLE item ALTER COLUMN id RESTART WITH 1;